# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  veganc++_config = debug
  sort_config = debug
endif
ifeq ($(config),release)
  veganc++_config = release
  sort_config = release
endif

PROJECTS := veganc++ sort

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

veganc++:
ifneq (,$(veganc++_config))
	@echo "==== Building veganc++ ($(veganc++_config)) ===="
	@${MAKE} --no-print-directory -C . -f veganc++.make config=$(veganc++_config)
endif

sort: veganc++
ifneq (,$(sort_config))
	@echo "==== Building sort ($(sort_config)) ===="
	@${MAKE} --no-print-directory -C . -f sort.make config=$(sort_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f veganc++.make clean
	@${MAKE} --no-print-directory -C . -f sort.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   veganc++"
	@echo "   sort"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"